
id: 1
name: Johnson Smith and Jones Co
amount: 345.33
remark: Pays on time
-


id: 2
name: Sam 'Mad Dog' Smith
amount: 993.44
remark: '  ' 
-


id: 3
name: Barney & Company
amount: 0
remark: Great to work with and always pays with cash
-


-

id: 1
name: Johnson Smith and Jones Co
amount: 345.33
remark: Pays on time


-

id: 2
name: Sam 'Mad Dog' Smith
amount: 993.44
remark: '  ' 


-

id: 3
name: Barney & Company
amount: 0
remark: Great to work with and always pays with cash

